version: '3.7'

services:
  db:
    build: ./
    container_name: mysql
    env_file:
      - .env
    cap_add:
      - SYS_NICE
    command:
      - --authentication_policy=mysql_native_password
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshakes
    volumes:
      - ./logs/data:/var/lib/mysql
      - ./logs/dump:/disk
    ports:
      - 33061:3306
    restart: always
