version: '3.7'

services:
  db:
    build: ./
    container_name: mysql
    env_file:
      - .env
    cap_add:
      - SYS_NICE
    command:
      - --authentication_policy=mysql_native_password
    volumes:
      - ./logs/data:/var/lib/mysql
      - ./logs/dump:/disk
    ports:
      - 33061:3306
    restart: always
