name: Deploy Frontend to Github Pages

on:
  push:
    branches:
      - master
    paths:
      - frontend/**

  pull_request:
    branches:
      - master
    paths:
      - frontend/**

jobs:
  deploy:
    name: CD Pipeline
    runs-on: ubuntu-20.04
    env:
      working-directory: './frontend'
    strategy:
      matrix:
        node-version: ['16.x']
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Install Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install Node.js dependencies
      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: npm install

      # Environment frontend/.env file
      - name: Environment frontend/.env file
        working-directory: ${{ env.working-directory }}
        run: |
          touch .env
          ENVS=$(cat <<EOF 
          ${{ secrets.FRONTEND_ENVS }}
          EOF)
          echo "$ENVS" >> .env
          cat .env

      # Build React
      - name: Build React
        working-directory: ${{ env.working-directory }}
        run: npm run build

      # Deploy to Github Pages
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: './frontend/build'
